import { createContext, useContext } from 'react'
import type { LanguageCode } from './types'
// Korean, English, Japanese, Traditional Chinese.
const labels = {
  chats: ['채팅', 'Chats', 'チャット', '聊天'], searchRooms: ['채팅방 검색', 'Search chats', 'チャット検索', '搜尋聊天室'], newChat: ['새 채팅', 'New chat', '新しいチャット', '新聊天'],
  name: ['이름', 'Name', '名前', '姓名'], country: ['국가', 'Country', '国', '國家'], language: ['사용 언어', 'Chat language', '使用言語', '使用語言'],
  welcome: ['언어는 달라도, 대화는 가깝게.', 'Different languages. Closer conversations.', '言葉が違っても、会話は近くに。', '語言不同，對話更靠近。'],
  intro: ['이름과 국가를 정하고 내 언어로 대화를 시작하세요.', 'Choose your name and country, then chat in your language.', '名前と国を選んで会話を始めましょう。', '選擇姓名與國家，用自己的語言聊天。'],
  signup: ['가입하고 시작하기', 'Join and start chatting', '登録して始める', '註冊並開始'], save: ['저장', 'Save', '保存', '儲存'], cancel: ['취소', 'Cancel', 'キャンセル', '取消'],
  countryNote: ['국가와 사용 언어는 별도로 선택할 수 있어요. 중국어는 번체를 지원합니다.', 'Choose country and language separately. Chinese uses Traditional characters.', '国と言語は別々に選べます。中国語は繁体字に対応します。', '國家與語言可分別選擇。中文支援繁體字。'],
  guestNote: ['비밀번호 없는 간단한 프로필입니다. 이 브라우저에서 다시 접속할 수 있어요.', 'A simple profile without a password. Return using this browser.', 'パスワードなしのプロフィールです。このブラウザで再接続できます。', '免密碼的個人檔案，可用此瀏覽器再次登入。'],
  profile: ['내 프로필', 'My profile', 'プロフィール', '個人檔案'], logout: ['로그아웃', 'Sign out', 'ログアウト', '登出'], summary: ['대화 요약', 'Conversation summary', '会話の要約', '對話摘要'], translation: ['번역 설정', 'Translation settings', '翻訳設定', '翻譯設定'], culture: ['문화 표현 설정', 'Cultural expressions', '文化表現設定', '文化表達設定'], members: ['멤버', 'Members', 'メンバー', '成員'], export: ['대화 내보내기', 'Export conversation', '会話を書き出す', '匯出對話'],
  searchMessages: ['대화 검색', 'Search messages', 'メッセージ検索', '搜尋訊息'], message: ['메시지 입력', 'Type a message', 'メッセージを入力', '輸入訊息'], send: ['전송', 'Send', '送信', '傳送'], back: ['채팅 목록', 'Chat list', 'チャット一覧', '聊天列表'], menu: ['메뉴', 'Menu', 'メニュー', '選單'], close: ['닫기', 'Close', '閉じる', '關閉'],
  empty: ['첫 메시지를 보내 대화를 시작하세요.', 'Send the first message to start a conversation.', '最初のメッセージを送りましょう。', '傳送第一則訊息開始對話。'],
  local: ['이 브라우저에 저장 · 예문 번역', 'Saved in this browser · example translations', 'このブラウザに保存・例文翻訳', '儲存在此瀏覽器・例句翻譯'], server: ['실시간 채팅', 'Live chat', 'リアルタイムチャット', '即時聊天'], ai: ['AI 번역 활성화', 'AI translation enabled', 'AI翻訳有効', 'AI翻譯已啟用'], noAi: ['AI 미연결 · 예문 번역만 제공', 'AI disconnected · example translations only', 'AI未接続・例文翻訳のみ', 'AI未連線・僅提供例句翻譯'],
  localNote: ['이 브라우저에만 저장됩니다. 다른 기기와 대화하거나 임의 문장을 AI 번역하려면 서버를 실행하세요.', 'Saved only in this browser. Run the server to chat across devices and translate arbitrary messages with AI.', 'このブラウザにのみ保存。端末間の会話や任意の文章のAI翻訳にはサーバーを起動してください。', '僅儲存在此瀏覽器。跨裝置聊天與任意文字AI翻譯需要啟動伺服器。'],
  connecting: ['연결 중…', 'Connecting…', '接続中…', '連線中…'], disconnected: ['연결 끊김 · 재연결 중', 'Disconnected · reconnecting', '切断・再接続中', '已斷線・重新連線中'],
  standard: ['기본 번역', 'Standard translation', '基本翻訳', '基本翻譯'], cultural: ['문화 맥락', 'Cultural context', '文化的な文脈', '文化語境'], explain: ['표현 설명', 'Explain expression', '表現の説明', '表達說明'], reveal: ['번역 보기', 'Show translation', '翻訳を見る', '顯示翻譯'], translating: ['번역 중…', 'Translating…', '翻訳中…', '翻譯中…'],
  unavailable: ['번역을 사용할 수 없어요 · 원문을 확인하세요', 'Translation unavailable · check the original', '翻訳できません・原文を確認してください', '無法翻譯・請查看原文'], offlineTranslation: ['예문 사전에 없는 문장입니다 · AI 연결이 필요해요', 'Phrase outside the example dictionary · connect AI', '例文辞書にない文章です・AI接続が必要です', '此句不在例句字典中・需要連接AI'], delivery: ['번역 결과', 'Translation results', '翻訳結果', '翻譯結果'], view: ['보기', 'View', '見る', '查看'], risk: ['상대에게 의도보다 강하게 들릴 수 있어요', 'This may sound stronger than intended.', '意図より強く聞こえる可能性があります。', '可能讓對方感受到比原意更強烈的語氣。'],
  loadingSummary: ['대화를 요약하는 중…', 'Summarizing…', '要約中…', '正在整理摘要…'], noSummary: ['아직 요약할 대화가 없어요.', 'No conversation to summarize yet.', 'まだ会話がありません。', '尚無可摘要的對話。'], summaryError: ['요약에 실패했어요. 잠시 후 다시 시도하세요.', 'Summary failed. Please try again shortly.', '要約に失敗しました。後で再度お試しください。', '摘要失敗，請稍後再試。'], extractive: ['AI 미연결: 최근 대화의 메시지를 발췌했습니다.', 'AI disconnected: excerpts from recent messages.', 'AI未接続：最近のメッセージを抜粋しました。', 'AI未連線：以下為近期訊息摘錄。'], decisions: ['결정·할 일', 'Decisions and tasks', '決定・タスク', '決定與任務'],
  roomName: ['채팅방 이름', 'Chat name', 'チャット名', '聊天室名稱'], selectMembers: ['함께 대화할 멤버', 'Choose participants', 'メンバーを選択', '選擇成員'], create: ['채팅방 만들기', 'Create chat', 'チャットを作成', '建立聊天室'], noPeople: ['다른 사용자가 아직 없어요. 다른 브라우저에서 가입하면 공용방에서 만날 수 있어요.', 'No other users yet. Join from another browser to meet in the global chat.', '他のユーザーはまだいません。別のブラウザから登録してください。', '尚無其他使用者，請從另一個瀏覽器註冊。'],
  onlinePeople: ['명', 'members', '人', '人'], languages: ['개 언어', 'languages', '言語', '種語言'], noResults: ['검색 결과가 없어요.', 'No results.', '検索結果がありません。', '沒有搜尋結果。'], busy: ['처리 중…', 'Working…', '処理中…', '處理中…'],
  storageError: ['브라우저에 저장하지 못했습니다. 저장 공간이나 설정을 확인하세요.', 'Could not save. Check browser storage and settings.', '保存できません。ブラウザの設定を確認してください。', '無法儲存，請檢查瀏覽器設定。'], signupError: ['저장하지 못했어요. 연결을 확인하고 다시 시도하세요.', 'Could not save. Check your connection and try again.', '保存できません。接続を確認してください。', '無法儲存，請檢查連線。'], sendError: ['전송하지 못했어요. 입력한 메시지는 유지됩니다.', 'Could not send. Your draft is preserved.', '送信できませんでした。入力内容は保持されています。', '傳送失敗，輸入內容已保留。'],
  all: ['항상 자동 번역', 'Always translate', '常に自動翻訳', '一律自動翻譯'], foreign: ['다른 언어만 자동 번역', 'Translate other languages', '他の言語だけ翻訳', '僅翻譯其他語言'], tap: ['탭할 때 번역', 'Translate on tap', 'タップで翻訳', '點選時翻譯'], off: ['사용 안 함', 'Off', 'オフ', '關閉'], important: ['중요한 표현', 'Important expressions', '重要な表現', '重要表達'], everyCulture: ['모든 문화 표현', 'All cultural expressions', 'すべての文化表現', '所有文化表達'], minimal: ['오해 위험이 높은 표현만', 'High misunderstanding risk only', '誤解のリスクが高い表現のみ', '僅容易誤解的表達'],
  alternative: ['더 부드러운 표현 사용', 'Use a gentler expression', 'より柔らかい表現を使う', '使用更溫和的表達'], meaning: ['의미', 'Meaning', '意味', '意思'], context: ['현재 문맥', 'Context', '文脈', '目前語境'], tone: ['말투·분위기', 'Tone', '口調', '語氣'], expression: ['표현', 'Expression', '表現', '表達'], original: ['원문', 'Original', '原文', '原文'], description: ['설명', 'Explanation', '説明', '說明'], region: ['지역', 'Region', '地域', '地區'],
} as const
export const LocaleContext = createContext<LanguageCode>('ko')
export const translate = (lang: LanguageCode, key: keyof typeof labels): string => labels[key][(['ko', 'en', 'ja', 'zh-TW'] as LanguageCode[]).indexOf(lang)]
export function useLocale() { const lang = useContext(LocaleContext); return { lang, t: (key: keyof typeof labels) => translate(lang, key) } }
